"""empty message

Revision ID: 2c819f3e5e7a
Revises: 3eafe784a115
Create Date: 2017-07-16 23:42:12.987000

"""

# revision identifiers, used by Alembic.
revision = '2c819f3e5e7a'
down_revision = '3eafe784a115'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
